Footprint index
Carbon-Knight/Front-End pull request #38
Opened 2021-01-13 16:16 UTC by s-steel

Footprint Index Page

## Description
Create service, poro, and facade for car_monthly_mileages for a user.
Create a footprint index page that shows a users previous car_monthly_mileages.
Each footprint has a link to edit, but this branch does not add the edit functionality.

## Motivation and Context
We need to user to be able to see their past footprints

## How Has This Been Tested?
All tests passing.
The backend response to this has not been merged to main yet.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] I have updated the README to reflect any changes.

2021-01-13 20:44 UTC, ETBassist approved these changes
Oh it's going to be interesting to see if this has any conflicts after the previous PR is merged in 😆

2021-01-13 21:07 UTC, c-bartell approved these changes

2021-01-14 03:15 UTC, carson-jardine requested changes
Since @jdcarey128 and I updated a bunch on the input-footprint branch from when you pulled it into this branch, I think it'll be best to pull our PR in first and then yours to handle any merge conflicts that come up!

2021-01-14 19:22 UTC, s-steel commented
I merged in the main branch fixed it up and all tests are passing.

2021-01-14 19:46 UTC, closed without merging